name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - main
      - dev

permissions:
  contents: write

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lint --scan

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --scan
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease --scan