name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - main
      - dev

permissions:
  contents: write

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3

      - name: Binary Compatibility Validation
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: apiCheck --scan

      - name: Lint
        uses: gradle/gradle-build-action@v3
        with:
          arguments: lint --scan

      - name: Test
        uses: gradle/gradle-build-action@v3
        with:
          arguments: test --scan
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleRelease --scan