name: "Demo Release"

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    name: "Build & Upload"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      - uses: actions/upload-artifact@v3
        with:
          name: transformerkt-demo
          path: demo/build/outputs/apk/release/demo-release.apk