name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  "Generate Documentation":
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup-java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: gradle refreshVersions
        uses: gradle/gradle-build-action@v2
        with:
          arguments: refreshVersions

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: transformerkt/build/dokka/html